### ISSUE TITLE
PocketItem Equals method is broken

### ISSUE THREAD

**Issue by fujiy** [ceee/PocketSharp#32]
It is broken here: https://github.com/ceee/PocketSharp/blob/master/PocketSharp/Models/PocketItem.cs#L414

**Comment by ceee** [comment]
Hi. Thanks for your PR.
I will add a failing unit test which checks the equality operator + equals and merge your changes afterwards.

**Comment by ceee** [comment]
I can't reproduce the fail. I have added the equality tests and they pass with the current implementation. See here: https://github.com/ceee/PocketSharp/commit/49436e0aaaff5dd045ca71fe37d944a5c7266329

Could you please provide more information on how and where it is broken and how to reproduce it?

**Comment by fujiy** [comment]
You need to pass a diferent type of object to Equals as argument, so the cast will fail

**Comment by ceee** [comment]
Thanks, confirmed.

**Comment by ceee** [comment]
Merged #34 and will update the NuGet package soon. Thanks for your contribution :)
