### ISSUE TITLE
version 5.0 add problem

### ISSUE THREAD

**Issue by ghost** [ceee/PocketSharp#39]
PocketClient.Add method in version 5.0 takes a very long time to complete and it was not the case in 4.2

**Comment by ceee** [comment]
The `Add` implementation has not changed. Where do you experience performance problems? Could you debug your code and see if it's a network bottleneck?

**Comment by ghost** [comment]
Unfortunately I have almost spent one whole work day in figuring out where the problem is as it made no sense but it was very reproducible.

What happens is that item doubles during the user initiated sync. First item is added to Pocket with the mentioned method when it is added to the app. However the result of the method is not returned for a long time (could be very well that the method is stuck until the next sync wakes it up by calling the PocketClient) and the item has no Pocket ID, and then the app figures out that it is the new item it doesn't have.

Reverting to 4.2 and it works as before.

It doesn't depend on the network it works like that in every situation from 3G to the optical internet.

**Comment by ceee** [comment]
By using a profiler you can see which method in your code or the library's code takes too long. In case it really was the `Add` method there was eventually a problem with the Pocket API.
