### ISSUE TITLE
Getting empty item titles

### ISSUE THREAD

**Issue by derekantrican** [ceee/PocketSharp#42]
As of today, I am getting empty titles for `PocketItems`. I am on version 5.0.0. Not sure if Pocket changed something about the API?

![image](https://user-images.githubusercontent.com/1558019/66948970-88626600-f00a-11e9-9d4f-b91a2d43b802.png)

**Comment by derekantrican** [comment]
It seems that the items also have no title on the Pocket web page:

![image](https://user-images.githubusercontent.com/1558019/66949394-4d146700-f00b-11e9-9f56-8e3324e6ab2b.png)

These items were added to Pocket via `PocketClient.Add`. Is this an issue on Pocket's end or an issue with `PocketClient.Add`?

**Comment by ceee** [comment]
Hi. This is definitely an issue on Pocket's end. Their article parser seems to fail to get titles from Youtube videos. The title should be there even if you don't add it via the `Add` method, as this property only overrides the default title.

**Comment by ceee** [comment]
Adding a YT video via an official "Add to pocket" button correctly stores and outputs the title.
No matter what, that's a problem with the public API (they are not using it themselves, so they don't have these probs). They stopped caring about the API years ago :-/

**Comment by derekantrican** [comment]
Good to know. I'll contact them. Thanks for the help
